/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo.app;

import demo.lib.Library;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Library library = new Library();
        if (library.someLibraryMethod() && library.experiment2()) {
            System.out.println(new App().getGreeting());
        }
    }
}
