/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/6.7.1/userguide/building_java_projects.html
 */
val VERSION: String by project
val GROUP: String by project
val COMPANY: String by project
val dep1: String by project

val CI: Boolean = "true".equals(System.getenv("CI"))
val TOKEN: String = System.getenv("TOKEN") ?: "DRY"
val GITHUB_REF: String = File(".git/HEAD").readLines()[0].replaceFirst(Regex("^ref: "), "")
val isMaster: Boolean = GITHUB_REF.equals("refs/heads/master")

fun bbbGroup(group: String): String {
    return if (CI && isMaster) group else "snapshots." + group
}

fun bbbVersion(version: String): String {
    return if (CI && isMaster) version else String.format("%08x", GITHUB_REF.hashCode()) + "-SNAPSHOT"
}

fun bbbRepo(group: String): String {
    return if (CI && isMaster) "$COMPANY/$group" else "$COMPANY/tmp-snapshots"
}

fun bbbRef(org: String): String {
    val parts = org.split(":")
    val g = bbbGroup(parts[0])
    val a = parts[1]
    val v = bbbVersion(parts[2])
    return "$g:$a:$v"
}

group = bbbGroup(GROUP)
version = bbbVersion(VERSION)
var packageRepo = bbbRepo(GROUP)

println("@@@@@@@@@@@     GITHUB_REF=$GITHUB_REF")
println("@@@@@@@@@@@        version=$version")
println("@@@@@@@@@@@          group=$group")
println("@@@@@@@@@@@    packageRepo=$packageRepo")

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    `maven-publish`
}

repositories {
    // Use JCenter for resolving dependencies.
    jcenter()
    mavenLocal()
    maven {
        url = uri("https://maven.pkg.github.com/$packageRepo")
        credentials {
            username = "" // can be anything but plugin requires it
            password = TOKEN
        }
    }
}

dependencies {
    // Use JUnit Jupiter API for testing.
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.6.2")

    // Use JUnit Jupiter Engine for testing.
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine")

    // This dependency is used by the application.
    implementation("com.google.guava:guava:29.0-jre")
    implementation(bbbRef(dep1))
}

application {
    // Define the main class for the application.
    mainClass.set("demo.app.App")
}

tasks.test {
    // Use junit platform for unit tests.
    useJUnitPlatform()
}
